on: 
 push:
   branches:
     - master  






jobs:
 build:
    runs-on: ubuntu-latest 

    steps:  
      
      - name: 'Login in dockerhup'
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
        
        - name: "Build Docker image"
          run: docker build -t ${{ secrets.USERNAME }}/myimage .

          - name: "Push to docker hub"
            run: docker push ${{ secrets.USERNAME }}/myimage
