on: 
 push:
   branches:
     - master  






jobs:
 build:
    runs-on: ubuntu-latest 

    steps:  
      - name: 'Testing Githup action'
        run: pwd

      - name: 'Login in dockerhup'
        run: docker login --username ${{ secrets.USERNAME }}  --password ${{ secrets.PASSWORD }}
