on: 
 push:
   branches:
    - master  






jobs:
 build:
    runs-on: ubun-latest 

    steps:  
      - name: 'Testing Githup action'
        run: pwd
        - name: 'Testing Githup printing'
        run: echo mohamed
